name: RSpec Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  rspec:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.3 # Change this to your desired Ruby version

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Run RSpec
      run: bundle exec rspec
