name: Ruby CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.3'  # Specify the Ruby version you want to use

    - name: Install dependencies
      run: |
        gem install bundler
        

    - name: Run tests
      run: |
        bundle exec rspec

